import os
import sys
from pydantic import BaseModel, Field
from langchain_core.prompts import ChatPromptTemplate
from dotenv import load_dotenv

sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
from src.core.llm import get_llm
from src.langgraph_app.agents.ingestion_agent import IngestionResult

load_dotenv(override=True)

class TriageResult(BaseModel):
    """Pydantic Schema for the structured routing decision."""
    priority: str = Field(description="The assigned priority: Urgent, High, Normal, or Low.")
    department: str = Field(description="The Aura Bank department to route to (e.g. Fraud, Tech Support, Billing, General CS).")
    rationale: str = Field(description="A brief 1-sentence explanation of why this priority and department were chosen.")

def run_triage_agent(ingestion_data: IngestionResult) -> TriageResult:
    """
    Evaluates the priority and routing of a ticket strictly based on the extracted
    Category, Tone, and Summary generated by the Ingestion Agent.
    """
    llm = get_llm(model_name="gpt-4o-mini", temperature=0.0)
    structured_llm = llm.with_structured_output(TriageResult)
    
    prompt = ChatPromptTemplate.from_messages([
        (
            "system", 
            "You are the Triage and Routing Agent for Aura Bank. You receive parsed ticket metadata. "
            "Assign a Priority (Urgent, High, Normal, Low) and a Department based on these rigid rules:\n\n"
            "PRIORITY RULES:\n"
            "- Urgent: Financial loss in progress (Active Fraud, Stolen Card), threat of legal action, or stranded customers.\n"
            "- High: Major security incidents or highly angry/frustrated tone.\n"
            "- Normal: Standard inquiries, neutral tone, technical issues (forgot PIN, app locked), and simple account management.\n"
            "- Low: Non-urgent feature requests, general feedback, positive tone.\n"
            "Do NOT categorize a ticket as High or Urgent simply because it is an inconvenience. Default to Normal unless safety or extreme anger is involved."
        ),
        (
            "human", 
            "Category: {category}\nTone: {tone}\nSummary: {summary}"
        )
    ])
    
    chain = prompt | structured_llm
    
    return chain.invoke({
        "category": ingestion_data.category,
        "tone": ingestion_data.tone,
        "summary": ingestion_data.summary
    })

def run_triage_node(state: dict) -> dict:
    """LangGraph node wrapper for the Triage Agent."""
    llm = get_llm(model_name="gpt-4o-mini", temperature=0.0)
    structured_llm = llm.with_structured_output(TriageResult)
    
    prompt = ChatPromptTemplate.from_messages([
        (
            "system", 
            "You are the Triage and Routing Agent for Aura Bank. You receive the customer's complaint text. "
            "Assign a Priority (Urgent, High, Normal, Low) and a Department based on these rigid rules:\n\n"
            "PRIORITY RULES:\n"
            "- Urgent: Financial loss in progress (Active Fraud, Stolen Card), threat of legal action, or stranded customers.\n"
            "- High: Major security incidents or highly angry/frustrated tone.\n"
            "- Normal: Standard inquiries, neutral tone, technical issues (forgot PIN, app locked), and simple account management.\n"
            "- Low: Non-urgent feature requests, general feedback, positive tone.\n"
            "Do NOT categorize a ticket as High or Urgent simply because it is an inconvenience. Default to Normal unless safety or extreme anger is involved."
        ),
        (
            "human", 
            "{masked_complaint}"
        )
    ])
    
    chain = prompt | structured_llm
    result = chain.invoke({"masked_complaint": state.get("masked_complaint", "")})
    
    return {
        "priority": result.priority,
        "department": result.department
    }
